#!/bin/bash

SCRIPT_DIR=$(dirname "$0")

echo "-----Uploads-----"
du -sh "$SCRIPT_DIR/../uploads"

echo ""

echo "-----Backups-----"
du -sh "$SCRIPT_DIR/../backups"

echo ""

echo "-----Disk-----"
df -h
